#COMPOSE.YAML
version: "3.8"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DATABASE_URL:  ${DATABASE_URL}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      GOOGLE_CLIENT_ID: tu-google-client-id
      GOOGLE_CLIENT_SECRET: tu-google-client-secret
      GITHUB_CLIENT_ID: tu-github-client-id
      GITHUB_CLIENT_SECRET: tu-github-client-secret
