# application.yml
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mvc:
    static-path-pattern: /**  # Actualizado para permitir todas las rutas estáticas
  output:
    ansi:
      enabled: always
  profiles:
    active: prod  # Perfil activo para producción

server:
  servlet:
    session:
      timeout: 30m
    encoding:
      charset: UTF-8
  port: ${PORT:8080}  # Usa variable de entorno PORT para Render

logging:
  level:
    root: info
    org.hibernate.SQL: debug
    org.springframework.web: WARN  # Reduce logging en producción

# Configuración específica para producción (perfil 'prod')
---
spring:
  config:
    activate:
      on-profile: prod
  web:
    resources:
      cache:
        period: 31536000  # 1 año de caché
  security:
    filter:
      order: 0