spring:
  config:
    activate:
      on-profile: dev  # Perfil específico para desarrollo
  datasource:
    url: jdbc:postgresql://localhost:5432/todoappdb
    username: todoappuser
    password: secretpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always