spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mvc:
    static-path-pattern: /**
  output:
    ansi:
      enabled: always
  profiles:
    active: dev  # Perfil por defecto para desarrollo

server:
  servlet:
    session:
      timeout: 30m
    encoding:
      charset: UTF-8
  port: ${PORT:8080}

logging:
  level:
    root: info
    org.hibernate.SQL: debug
    org.springframework.web: WARN

---
# Configuración de PRODUCCIÓN (se activa con perfil 'prod')
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: never

server:
  compression:
    enabled: true

logging:
  file:
    name: application.log