#application-prod.yml
spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000 # 30 segundos
      maximum-pool-size: 5 # Render recomienda pools pequeños
  jpa:
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: never

server:
  port: ${PORT:8080}
  compression:
    enabled: true

logging:
  file:
    name: application.log